In [155]:
import pylab
import matplotlib as mpl
import pandas as pd
import scipy as scp
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from scipy.interpolate import UnivariateSpline
%pylab inline
pylab.rcParams['figure.figsize'] = (10.0, 8.0) # set size of figures"
plt.rcParams.update({'font.size': 18})
from scipy.stats import f_oneway

#new stuff
from scipy.stats import friedmanchisquare
from scipy.stats import chisqprob

Populating the interactive namespace from numpy and matplotlib

WARNING: pylab import has clobbered these variables: ['pylab']
`%matplotlib` prevents importing * from pylab and numpy

<h1> Example usage of Friedman Test using a uniform distribution </h1>

In [2]:
#Friendman test with uniform distrubuation
chi2, p = friedmanchisquare(np.random.uniform(0,10,100),np.random.uniform(0,10,100),np.random.uniform(0,10,100))
print('p value = '+'{:0.2f}'.format(p*100)+'%')
#p value of 5 to 90 % is good agreement

p value = 88.69%

<h3> This loads in the data </h3>

In [3]:
Ani=pd.read_excel('/Users/attiladobi/Documents/Ani/sept_oct2013.xlsx',skiprows=0)
#Ani=pd.read_excel('data/sept_oct2013.xlsx',skiprows=0)
Time=array(Ani['Time'].T,dtype='datetime64')
Ani['Hour']=pd.DatetimeIndex(Ani['Time']).hour #allows to sort by hours of the day
Ani['Day']=pd.DatetimeIndex(Ani['Time']).day #sort by hours of the day
Ani['Month']=pd.DatetimeIndex(Ani['Time']).month #sort by hours of the day

<h1> List the available keys </h1>

In [14]:
Ani.keys()

Index([ u'Time',   u'TS2',   u'HS2',   u'DS2',  u'TSh6',  u'HSh6',  u'DSh6',
        u'TSh7',  u'HSh7',  u'DSh7',  u'TS10',  u'HS10',  u'DS10', u'TSh16',
       u'HSh16', u'DSh16', u'TSh17',  u'Sh17', u'DSh17',  u'TS19',  u'HS19',
        u'DS19', u'TSh19', u'HSh19', u'DSh19',  u'TS27',  u'HS27',  u'DS27',
        u'TS29',  u'HS29',  u'DS29',  u'TS32',  u'HS32',  u'DS32', u'TSh33',
       u'HSh33', u'DSh33',  u'TS34',  u'HS34',  u'DS34', u'TSh35', u'HSh35',
       u'DSh35',  u'TS37',  u'HS37',  u'DS37', u'TSh42', u'HSh42', u'DSh42',
         u'TK5',   u'HK5',   u'DK5',   u'TK8',   u'HK8',   u'DK8',  u'Hour'],
      dtype='object')

<h1> Pull out temperature data by hour, build a dictionary of all sensors </h1>

In [69]:
vals_hour=[]
hours=np.arange(0,24)
for hour in hours:
    vals=[]
    for key in Ani.keys():
        if not (key == 'Time'): #skip the time key
            vals.append(Ani[key].loc[Ani['Hour']==hour].mean())
    vals_hour.append(vals)
#convert to a numpy array
vals_hour=np.array(vals_hour)
Ani_hourly=dict((key, vals_hour[:,ii]) for ii, key in enumerate(Ani.keys()[1:]))

<h1> The previous code is brute force, much simpler using groupy in pandas </h1>

In [149]:
#This will group by hour and find the mean for each sensor (same as above)
Ani_hourly=Ani.groupby('Hour').mean()

In [150]:
Ani_hourly

,TS2,HS2,DS2,TSh6,HSh6,DSh6,TSh7,HSh7,DSh7,TS10,...,HSh42,DSh42,TK5,HK5,DK5,TK8,HK8,DK8,Day,Month
Hour,,,,,,,,,,,,,,,,,,,,,
0,9.507051,64.657692,3.099615,9.516667,63.911538,2.956154,9.660897,61.295513,2.493205,9.679167,...,59.739744,2.576154,8.525000,63.352083,1.875417,7.897222,64.080556,1.430556,25.357143,9.571429
1,8.625641,67.332692,2.824872,8.638462,66.707051,2.722564,8.650641,63.982692,2.147308,8.766667,...,62.853846,2.187949,7.737500,67.283333,1.955000,6.869444,66.730556,0.952222,25.357143,9.571429
2,7.824359,69.430128,2.495513,7.888462,68.701923,2.425256,7.883974,65.992949,1.852308,7.995238,...,65.124359,1.930128,7.172917,69.833333,1.926250,6.436111,70.072222,1.233333,25.357143,9.571429
3,6.879487,71.608333,2.022821,7.034615,70.430128,1.956154,7.030128,67.570513,1.368077,7.054167,...,66.799359,1.382179,6.187500,71.668750,1.308333,5.833333,70.794444,0.786111,25.357143,9.571429
4,6.221795,74.169872,1.886026,6.318590,72.755769,1.722179,6.335897,69.848718,1.174872,6.354762,...,68.704487,1.184103,5.618750,72.929167,0.966667,5.191667,71.736111,0.360000,25.357143,9.571429
5,6.000000,75.017337,1.825798,6.090153,73.920250,1.720666,6.056172,70.965326,1.118308,6.167093,...,70.785714,1.230374,5.897790,70.317680,0.671271,5.770000,69.240000,0.351333,25.357143,9.571429
6,5.395455,75.840152,1.395909,5.514394,74.348485,1.245606,5.481818,71.701515,0.708182,5.473611,...,71.831061,0.846364,5.825000,66.262500,-0.205000,5.791667,67.687500,0.105833,25.357143,9.571429
7,6.038636,74.566667,1.746515,6.202273,73.477273,1.711667,6.331818,70.529545,1.233030,5.544444,...,71.981818,1.175455,5.508333,65.841667,-0.584167,5.370833,67.975000,-0.198333,25.357143,9.571429
8,14.864394,55.434091,4.922576,11.419697,62.696970,4.191970,12.190909,59.728788,4.079848,11.526389,...,64.037879,3.981970,8.691667,61.266667,0.984167,8.395833,63.470833,1.403333,25.357143,9.571429
9,23.585606,37.623485,6.393333,15.642965,52.060514,5.287595,15.650000,51.384091,5.088636,21.448611,...,55.789394,5.033030,17.337500,45.945833,4.447500,17.183333,46.533333,4.568333,25.357143,9.571429
10,31.337179,24.416667,6.687692,21.331410,37.946795,5.415513,21.040385,38.209615,5.205000,31.234524,...,41.602564,4.573974,25.746606,25.400452,2.923529,26.946875,22.009375,1.658750,24.928571,9.500000
11,38.271154,16.211538,6.373333,26.198077,27.279487,4.581154,25.989744,27.596154,4.512821,38.763095,...,31.254487,3.678846,29.983333,16.261111,0.566111,33.725000,11.570833,-0.823333,24.928571,9.500000
12,41.935047,11.723951,4.810825,29.853857,20.636671,3.419350,29.995264,20.306495,3.252233,43.941176,...,23.418133,1.871719,33.566667,12.325000,-0.444444,36.404167,10.300000,-0.895000,26.156446,9.474343
13,42.225694,9.696528,2.874167,32.661806,15.990278,2.313750,32.915278,15.706250,2.259028,46.250641,...,18.110417,0.722083,35.822222,10.427778,-0.427778,37.562500,9.308333,-0.813333,26.769231,9.461538
14,40.999306,9.479167,1.564167,33.579167,13.833333,1.429583,34.095139,13.405556,1.491944,46.561538,...,15.096528,0.082083,37.430556,10.188889,0.799444,38.454167,9.479167,0.537500,26.769231,9.461538
15,39.989583,10.054167,2.045972,33.325694,14.248611,1.943889,33.798611,13.818056,1.921111,43.940385,...,15.743750,0.991250,37.205556,10.308333,0.539444,38.079167,8.804167,-0.943333,26.769231,9.461538
16,38.811806,11.242361,2.699306,32.216667,15.853472,2.507778,32.669444,15.421528,2.466806,40.791667,...,17.713889,1.800972,35.794444,11.591667,0.751111,36.012500,9.979167,-1.201667,26.769231,9.461538
17,35.631944,13.170833,2.437917,30.103472,17.781944,2.419028,30.466667,17.381944,2.374583,35.892949,...,19.540278,2.174306,33.880556,12.916667,0.787222,33.079167,11.800000,-1.229167,26.769231,9.461538
18,30.342361,17.250694,2.056389,28.174306,20.287500,2.705139,27.965278,20.217361,2.499722,30.625641,...,21.740972,2.646111,30.072222,16.858333,1.856111,28.262500,17.337500,0.636667,26.769231,9.461538
19,22.359028,27.343750,2.099722,22.771528,27.556944,2.534167,23.044444,27.161111,2.582917,22.997436,...,28.277083,3.140556,22.255556,26.541667,1.823333,21.183333,26.641667,0.894167,26.769231,9.461538
20,18.323077,36.603205,2.959615,18.132692,37.267308,3.069487,18.553846,36.492308,3.142179,18.607738,...,37.057692,4.011282,18.152083,35.912500,2.716667,16.772222,36.919444,1.889444,26.500000,9.500000
21,15.657051,44.944231,3.596538,15.429487,45.212179,3.488333,15.873718,44.158333,3.556538,15.822024,...,43.982051,4.295256,15.262500,43.468750,2.794583,13.780556,46.288889,2.375000,26.500000,9.500000
22,13.483333,52.410256,3.830641,13.266026,52.148718,3.567564,13.630769,50.737821,3.512051,13.465476,...,50.145513,4.028077,12.485417,51.883333,2.794583,10.902778,55.088889,2.180000,26.500000,9.500000
23,11.188462,59.408974,3.472179,11.150000,58.792949,3.305128,11.421795,56.825000,3.068077,11.280952,...,55.762179,3.401795,10.679167,58.172917,2.730000,9.227778,60.533333,1.905000,26.500000,9.500000

<h1> Now, we will want to groupy hour on a daily and monthly basis </h1>

In [137]:
#This will group by hour and find the mean for each sensor (same as above)
Ani_hourly_all=Ani.loc[(Ani.Hour>10) & (Ani.Hour<15)].groupby(['Month','Day','Hour']).mean()
#~isnan(Ani.TS2) & ~isnan(Ani.TS10) & ~isnan(Ani.TS19) & ~isnan(Ani.TS27)& ~isnan(Ani.TS37)

In [138]:
Ani_hourly_all

                      TS2        HS2        DS2       TSh6       HSh6  \
Month Day Hour
9     24  11          NaN        NaN        NaN        NaN        NaN
          12          NaN        NaN        NaN        NaN        NaN
          13          NaN        NaN        NaN        NaN        NaN
          14          NaN        NaN        NaN        NaN        NaN
      25  11    41.191667  11.066667   4.936667  26.350000  18.933333
          12    46.150000   9.633333   6.623333  29.783333  17.391667
          13    50.116667   7.683333   6.266667  32.908333  13.908333
          14    44.116667   8.425000   3.171667  33.258333  13.066667
      26  11    35.283333  22.091667  10.261667  20.425000  45.491667
          12    43.058333  14.433333  10.136667  26.066667  31.758333
          13    49.225000   8.625000   7.175000  32.108333  17.516667
          14    47.833333   5.941667   0.995000  33.566667  10.991667
      27  11    24.666667  37.058333   8.468333  17.358333  51.266667
          12    34.650000  21.083333   9.133333  20.741667  42.350000
          13    40.708333  15.491667   9.385000  23.933333  34.525000
          14    37.491667  14.283333   5.750000  26.116667  26.391667
      28  11    36.458333  10.683333   0.588333  27.266667  15.400000
          12    41.841667   7.300000  -0.611667  30.091667  11.341667
          13    43.725000   5.350000  -3.321667  32.566667   8.383333
          14    48.758333   4.633333  -1.770000  35.258333   7.633333
      29  11    34.658333   9.483333  -2.171667  26.791667  13.366667
          12    35.791667   7.658333  -4.225000  29.950000  10.633333
          13    37.758333   5.866667  -6.253333  32.083333   7.900000
          14    40.125000   4.908333  -6.913333  31.608333   7.016667
      30  11    39.200000  10.050000   1.918333  24.466667  19.250000
          12    46.416667   6.541667   1.265000  29.875000  12.833333
          13    43.075000   6.700000  -0.710000  31.350000  11.483333
          14    44.566667   6.416667  -0.271667  32.691667  10.708333
10    1   11    25.650000  28.625000   6.001667  27.308333  27.700000
          12    22.342105  35.526316   6.278947  22.315789  35.368421
      24  11    42.716667  15.850000  11.311667  28.166667  29.950000
          12    48.283333  10.208333   8.988333  32.158333  19.575000
          13    42.150000   9.541667   3.521667  34.400000  15.300000
          14    37.433333  10.675000   1.573333  33.850000  14.616667
      25  11    42.358333  15.591667  10.646667  26.000000  33.258333
          12    42.591667   9.508333   3.793333  31.516667  17.466667
          13    37.033333  10.941667   1.591667  32.058333  15.608333
          14    35.741667  10.433333  -0.041667  32.608333  13.850000
      26  11    45.825000   7.858333   3.443333  30.325000  15.825000
          12    48.591667   5.375000   0.086667  35.241667  10.350000
          13    44.566667   5.391667  -2.656667  37.683333   8.933333
          14    42.108333   8.300000   1.530000  38.308333  11.433333
      27  11    48.025000   9.150000   7.255000  32.125000  18.733333
          12    41.875000  10.475000   4.655000  34.591667  16.166667
          13    39.675000  12.250000   5.240000  36.133333  15.991667
          14    39.183333  13.150000   5.861667  37.050000  15.933333
      28  11    36.941667  20.175000  10.345000  24.866667  38.191667
          12    38.841667  18.150000  10.315000  27.808333  32.366667
          13    40.966667  15.566667   9.725000  31.716667  25.475000
          14    37.625000  11.916667   3.113333  33.516667  16.666667
      29  11    44.550000  13.066667   9.848333  29.125000  27.266667
          12    41.333333  12.783333   7.105000  32.808333  20.741667
          13    37.708333  12.950000   4.526667  35.000000  16.858333
          14    37.008333  14.666667   5.771667  35.116667  17.691667

                    DSh6       TSh7       HSh7      DSh7       TS10    ...     \
Month Day Hour                                                         ...
9     24  11         NaN        NaN        NaN       NaN  47.425000    ...
          12         NaN        NaN        NaN       NaN  51.550000    ...
          13         NaN        NaN        NaN       NaN  51.166667    ...
          14         NaN        NaN        NaN       NaN  50.450000    ...
      25  11    0.845000  26.975000  19.075000  1.468333  41.850000    ...
          12    2.426667  30.216667  17.750000  3.066667  44.641667    ...
          13    1.810000  32.958333  14.591667  2.518333  45.975000    ...
          14    1.198333  33.866667  13.650000  2.270000  47.491667    ...
      26  11    8.188333  20.116667  46.458333  8.206667  37.750000    ...
          12    7.841667  26.441667  31.850000  8.216667  45.250000    ...
          13    4.201667  32.308333  17.900000  4.713333  48.516667    ...
          14   -0.960000  34.233333  11.266667 -0.105000  50.150000    ...
      27  11    7.186667  16.616667  53.366667  7.088333  25.416667    ...
          12    7.465000  20.800000  42.508333  7.576667  36.641667    ...
          13    7.281667  23.508333  35.458333  7.320000  42.525000    ...
          14    5.313333  26.483333  26.358333  5.603333  41.200000    ...
      28  11   -1.431667  26.725000  16.216667 -1.145000  38.950000    ...
          12   -3.230000  29.758333  11.850000 -2.895000  44.500000    ...
          13   -5.331667  32.650000   8.916667 -4.458333  45.716667    ...
          14   -4.576667  35.691667   8.175000 -3.355000  50.733333    ...
      29  11   -3.530000  26.100000  14.175000 -3.296667  36.808333    ...
          12   -4.196667  29.375000  11.308333 -3.836667  37.775000    ...
          13   -6.465000  31.441667   8.700000 -5.683333  40.150000    ...
          14   -8.335000  31.491667   7.716667 -7.185000  42.250000    ...
      30  11   -0.588333  24.691667  19.550000 -0.203333  42.533333    ...
          12   -1.740000  30.333333  12.983333 -1.218333  45.866667    ...
          13   -2.053333  31.658333  11.841667 -1.386667  46.375000    ...
          14   -1.973333  33.233333  11.125000 -1.065000  47.558333    ...
10    1   11    6.953333  26.258333  31.333333  7.768333  25.441667    ...
          12    6.247368  22.210526  36.000000  6.436842  21.289474    ...
      24  11    8.865000  28.158333  29.833333  8.780000  39.758333    ...
          12    5.925000  31.950000  18.883333  5.233333  43.508333    ...
          13    4.286667  34.925000  14.691667  4.115000  47.425000    ...
          14    3.228333  34.325000  13.658333  2.635000  44.325000    ...
      25  11    8.373333  26.066667  32.733333  8.191667  42.083333    ...
          12    3.813333  31.925000  16.425000  3.251667  45.266667    ...
          13    2.748333  32.650000  14.491667  2.173333  43.841667    ...
          14    1.503333  33.100000  12.741667  0.718333  42.366667    ...
      26  11    1.481667  30.258333  14.783333  0.471667  48.158333    ...
          12   -0.581667  35.441667   9.200000 -2.061667  50.683333    ...
          13   -0.686667  38.408333   7.808333 -1.993333  50.966667    ...
          14    3.221667  38.841667  10.150000  1.978333  49.975000    ...
      27  11    5.338333  31.833333  17.808333  4.365000  41.933333    ...
          12    5.253333  35.141667  14.908333  4.521667  47.183333    ...
          13    6.323333  36.916667  14.508333  5.541667  48.866667    ...
          14    7.005000  37.816667  14.441667  6.193333  48.083333    ...
      28  11    9.621667  24.958333  37.191667  9.323333  33.875000    ...
          12    9.755000  27.775000  31.616667  9.370000  40.033333    ...
          13    9.486667  32.116667  24.200000  9.056667  43.708333    ...
          14    4.586667  34.183333  15.408333  3.935000  44.800000    ...
      29  11    8.251667  29.108333  26.225000  7.648333  40.700000    ...
          12    7.405000  33.250000  19.425000  6.793333  45.508333    ...
          13    6.163333  35.441667  15.366667  5.191667  46.025000    ...
          14    6.943333  35.875000  16.175000  6.280000  45.916667    ...

                    DS37      TSh42      HSh42     DSh42        TK5  \
Month Day Hour
9     24  11         NaN        NaN        NaN       NaN  33.425000
          12         NaN        NaN        NaN       NaN  37.366667
          13         NaN        NaN        NaN       NaN  37.958333
          14         NaN        NaN        NaN       NaN  38.308333
      25  11         NaN  22.866667  21.808333 -0.073333  27.041667
          12         NaN  25.325000  21.408333  1.670000  30.616667
          13         NaN  27.866667  17.516667  1.006667  33.866667
          14         NaN  30.050000  16.008333  1.476667  36.216667
      26  11    9.106667  18.533333  50.175000  7.920000        NaN
          12    7.585000  22.975000  36.208333  7.101667        NaN
          13    2.701667  26.925000  20.483333  2.213333        NaN
          14   -2.088333  29.333333  11.758333 -3.288333        NaN
      27  11    7.333333  12.125000  67.533333  6.288333        NaN
          12    7.781667  15.891667  54.991667  6.810000        NaN
          13    7.746667  19.766667  43.025000  6.781667        NaN
          14    5.045000  23.433333  30.200000  4.946667        NaN
      28  11    0.108333  25.683333  16.325000 -1.881667        NaN
          12   -2.645000  27.925000  11.866667 -4.266667        NaN
          13   -5.323333  30.108333   8.891667 -6.415000        NaN
          14   -5.748333  30.666667   8.516667 -6.535000        NaN
      29  11   -3.148333  24.516667  14.933333 -3.866667        NaN
          12   -5.543333  26.325000  11.900000 -5.528333        NaN
          13   -7.726667  27.975000   9.058333 -7.743333        NaN
          14   -8.241667  28.483333   8.008333 -8.915000        NaN
      30  11   -0.526667  22.691667  20.100000 -1.458333        NaN
          12   -2.931667  26.675000  13.633333 -3.415000        NaN
          13   -2.025000  28.383333  12.791667 -2.903333        NaN
          14   -2.466667  28.875000  12.300000 -3.080000        NaN
10    1   11    6.695000  25.141667  35.166667  8.443333        NaN
          12    7.163158  22.263158  38.315789  7.278947        NaN
      24  11         NaN  24.791667  30.575000  6.230000  29.483333
          12         NaN  28.458333  18.325000  1.930000  32.716667
          13         NaN  31.383333  14.575000  1.263333  35.641667
          14         NaN  33.008333  13.200000  1.151667  37.766667
      25  11    7.575000  23.558333  36.008333  7.380000        NaN
          12    0.998333  28.250000  17.600000  1.261667        NaN
          13    0.793333  30.041667  15.500000  1.041667        NaN
          14   -0.683333  29.875000  13.800000 -0.718333        NaN
      26  11    0.641667  28.583333  14.841667 -0.805000        NaN
          12   -3.711667  32.508333   9.450000 -3.863333        NaN
          13   -4.515000  34.416667   8.200000 -4.285000        NaN
          14    0.575000  34.500000  11.933333  0.906667        NaN
      27  11    4.160000  28.708333  20.516667  3.846667        NaN
          12    4.283333  31.483333  17.658333  4.013333        NaN
          13    5.283333  33.475000  16.416667  4.568333        NaN
          14    5.865000  34.566667  16.716667  5.710000        NaN
      28  11    9.485000  20.450000  47.191667  8.800000        NaN
          12    9.256667  23.233333  39.825000  8.820000        NaN
          13    8.396667  26.508333  32.041667  8.421667        NaN
          14    3.345000  30.025000  18.991667  3.441667        NaN
      29  11    7.106667  25.400000  31.133333  7.001667        NaN
          12    6.510000  29.233333  23.433333  6.215000        NaN
          13    4.671667  31.208333  18.825000  4.715000        NaN
          14    5.851667  31.825000  19.725000  5.888333        NaN

                      HK5       DK5        TK8        HK8       DK8
Month Day Hour
9     24  11     8.425000 -4.681667  37.108333   8.050000 -2.583333
          12     6.450000 -5.293333  39.975000   6.175000 -4.003333
          13     6.875000 -4.048333  39.850000   6.600000 -3.231667
          14     8.525000 -0.871667  39.583333   8.150000 -0.576667
      25  11    17.450000  0.293333  30.341667  15.091667  0.936667
          12    16.333333  2.198333  32.833333  14.425000  2.213333
          13    12.958333  1.565000  35.275000  12.016667  1.605000
          14    11.800000  2.023333  37.325000  10.808333  1.651667
      26  11          NaN       NaN        NaN        NaN       NaN
          12          NaN       NaN        NaN        NaN       NaN
          13          NaN       NaN        NaN        NaN       NaN
          14          NaN       NaN        NaN        NaN       NaN
      27  11          NaN       NaN        NaN        NaN       NaN
          12          NaN       NaN        NaN        NaN       NaN
          13          NaN       NaN        NaN        NaN       NaN
          14          NaN       NaN        NaN        NaN       NaN
      28  11          NaN       NaN        NaN        NaN       NaN
          12          NaN       NaN        NaN        NaN       NaN
          13          NaN       NaN        NaN        NaN       NaN
          14          NaN       NaN        NaN        NaN       NaN
      29  11          NaN       NaN        NaN        NaN       NaN
          12          NaN       NaN        NaN        NaN       NaN
          13          NaN       NaN        NaN        NaN       NaN
          14          NaN       NaN        NaN        NaN       NaN
      30  11          NaN       NaN        NaN        NaN       NaN
          12          NaN       NaN        NaN        NaN       NaN
          13          NaN       NaN        NaN        NaN       NaN
          14          NaN       NaN        NaN        NaN       NaN
10    1   11          NaN       NaN        NaN        NaN       NaN
          12          NaN       NaN        NaN        NaN       NaN
      24  11    22.908333  6.086667        NaN        NaN       NaN
          12    14.191667  1.761667        NaN        NaN       NaN
          13    11.450000  1.200000        NaN        NaN       NaN
          14    10.241667  1.246667        NaN        NaN       NaN
      25  11          NaN       NaN        NaN        NaN       NaN
          12          NaN       NaN        NaN        NaN       NaN
          13          NaN       NaN        NaN        NaN       NaN
          14          NaN       NaN        NaN        NaN       NaN
      26  11          NaN       NaN        NaN        NaN       NaN
          12          NaN       NaN        NaN        NaN       NaN
          13          NaN       NaN        NaN        NaN       NaN
          14          NaN       NaN        NaN        NaN       NaN
      27  11          NaN       NaN        NaN        NaN       NaN
          12          NaN       NaN        NaN        NaN       NaN
          13          NaN       NaN        NaN        NaN       NaN
          14          NaN       NaN        NaN        NaN       NaN
      28  11          NaN       NaN        NaN        NaN       NaN
          12          NaN       NaN        NaN        NaN       NaN
          13          NaN       NaN        NaN        NaN       NaN
          14          NaN       NaN        NaN        NaN       NaN
      29  11          NaN       NaN        NaN        NaN       NaN
          12          NaN       NaN        NaN        NaN       NaN
          13          NaN       NaN        NaN        NaN       NaN
          14          NaN       NaN        NaN        NaN       NaN

[54 rows x 54 columns]

<h1> Here we'll do the Friendman test broken down by each sensor </h1>

<h1> Setup time range </h1>

In [151]:
#set hour range
time_start=10
time_end =15
cut=range(time_start,time_end)

<h1> Friedman test of all the sun back sensors </h1>

In [167]:
chi2, p = friedmanchisquare(Ani_hourly['TS2'][cut],Ani_hourly['TS10'][cut],Ani_hourly['TS19'][cut])
print ('chi^2 =',chi2,' p= ', p)
print('p value = '+'{:0.2f}'.format(p*100)+'%')

('chi^2 =', 6.4000000000000057, ' p= ', 0.040762203978366107)
p value = 4.08%

<h2> Sun back, the entire data set averaged every hour </h2>

In [168]:
chi2, p = friedmanchisquare(Ani_hourly_all['TS2'],Ani_hourly_all['TS10'],Ani_hourly_all['TS19'])
print ('chi^2 =',chi2,' p= ', p)
print('p value = '+'{:0.2f}'.format(p*100)+'%')

('chi^2 =', 40.333333333333258, ' p= ', 1.7447288735863923e-09)
p value = 0.00%

<h1> Sun front, hourly average </h1>

In [169]:
chi2, p = friedmanchisquare(Ani_hourly['TS27'][cut],Ani_hourly['TS29'][cut],Ani_hourly['TS32'][cut],\
                            Ani_hourly['TS34'][cut],Ani_hourly['TS37'][cut])
print ('chi^2 =',chi2,' p= ', p)
print('p value = '+'{:0.2f}'.format(p*100)+'%')
#hmm, these are quite different

('chi^2 =', 19.359999999999999, ' p= ', 0.00066772966031508044)
p value = 0.07%

In [170]:
chi2, p = friedmanchisquare(Ani_hourly_all['TS27'],Ani_hourly_all['TS29'],Ani_hourly_all['TS32'],\
                            Ani_hourly_all['TS34'],Ani_hourly_all['TS37'])
print ('chi^2 =',chi2,' p= ', p)
print('p value = '+'{:0.2f}'.format(p*100)+'%')
#hmm, these are quite different

('chi^2 =', 115.94810009267844, ' p= ', 3.9160743196450137e-24)
p value = 0.00%

In [171]:
chi2, p = friedmanchisquare(Ani_hourly_all['TS27'],Ani_hourly_all['TS29'],Ani_hourly_all['TS37'])
print ('chi^2 =',chi2,' p= ', p)
print('p value = '+'{:0.2f}'.format(p*100)+'%')

('chi^2 =', 10.037037037036953, ' p= ', 0.0066143184446752915)
p value = 0.66%

<h1> How different three sun-back sensors from the five sun-front sensors? </h1>

In [172]:
chi2, p = friedmanchisquare(Ani_hourly['TS2'][cut],Ani_hourly['TS10'][cut],Ani_hourly['TS19'][cut]\
                           ,Ani_hourly['TS27'][cut],Ani_hourly['TS29'][cut],Ani_hourly['TS32'][cut]\
                            ,Ani_hourly['TS34'][cut],Ani_hourly['TS37'][cut] )
print ('chi^2 =',chi2,' p= ', p)
print('p value = '+'{:0.5f}'.format(p*100)+'%')

('chi^2 =', 33.0, ' p= ', 2.6476442940650662e-05)
p value = 0.00265%

<h1> How different three sun-back sensors from the average of sun-front </h1>

In [173]:
chi2, p = friedmanchisquare(Ani_hourly['TS2'][cut],Ani_hourly['TS10'][cut],Ani_hourly['TS19'][cut]\
                           ,mean( (Ani_hourly['TS27'][cut],Ani_hourly['TS29'][cut],Ani_hourly['TS32'][cut]\
                            ,Ani_hourly['TS34'][cut],Ani_hourly['TS37'][cut]),0) )
print ('chi^2 =',chi2,' p= ', p)
print('p value = '+'{:0.4f}'.format(p*100)+'%')

('chi^2 =', 12.840000000000003, ' p= ', 0.0049957060439281822)
p value = 0.4996%

<h1 style="color:red;"> In the following we do it in groups, and also with a Chi^2 test </h1>

<h3> Friedman test for the means of the sensors broken up into four catigories 
   <ul>
    <li> sun_ave_front </li>
    <li> sun_ave_back </li>
    <li> shade_ave_all </li>
    <li> control </li>
   </ul>
</h3>

<h1> Define function to sort data time of day, return means and standard deviation </h1>

In [176]:
def get_ave_values(str1='T'):
    shade_ave_all=[]
    sun_ave_front=[]
    sun_ave_back=[]
    con_ave_all=[]
    shade_std_all=[]
    sun_std_front=[]
    sun_std_back=[]
    con_std_all=[]
    hours=np.arange(0,24)
    for hour in hours:
        means_sun_back=[]
        means_sun_front=[]
        means_shade=[]
        means_con=[]
        for key in Ani.keys():
            if (key[0:3]==str1+'Sh'):
                means_shade.append(Ani[key].loc[Ani['Hour']==hour].mean())
                #print(key,Ani[key].loc[Ani['Hour']==hour].mean())
            elif ((key[0:3]==str1+'S2') | (key[0:4]==str1+'S10') | (key[0:4]==str1+'S19') ) :
                means_sun_back.append(Ani[key].loc[Ani['Hour']==hour].mean())
            elif (key[0:2]==str1+'S'):
                means_sun_front.append(Ani[key].loc[Ani['Hour']==hour].mean())
            elif (key[0:2]==str1+'K'):
                means_con.append(Ani[key].loc[Ani['Hour']==hour].mean())
        shade_ave_all.append(mean(means_shade))
        shade_std_all.append(std(means_shade))
        sun_ave_back.append(mean(means_sun_back))
        sun_std_back.append(std(means_sun_back))
        sun_ave_front.append(mean(means_sun_front))
        sun_std_front.append(std(means_sun_front))
        con_ave_all.append(mean(means_con))
        con_std_all.append(std(means_con))
    return sun_ave_back, sun_std_back, sun_ave_front, sun_std_front, shade_ave_all, shade_std_all, con_ave_all, con_std_all

<h1> Test hypothosis that three independent measurements are the same. Below: select the time range and compute the mean and standard deviation</h1>

In [178]:
sun_ave_back, sun_std_back, sun_ave_front, sun_std_front, shade_ave_all, shade_std_all, con_ave_all, con_std_all = get_ave_values('T')

In [193]:
#set time range
start_h=10
end_hour=15
hour_diff=end_hour-start_h 

sun_back_test=np.array([])
sun_front_test=np.array([])
shade_test=np.array([])
cont_test=np.array([])
std_sun_back_test=np.array([])
std_sun_front_test=np.array([])
std_shade_test=np.array([])
std_cont_test=np.array([])


for hour in range(start_h,end_hour):
    sun_back_test= hstack((sun_back_test,sun_ave_back[hour]))
    sun_front_test= hstack((sun_front_test,sun_ave_front[hour]))
    shade_test= hstack((shade_test,shade_ave_all[hour]))
    cont_test= hstack((cont_test,con_ave_all[hour]))
    #get std
    std_sun_back_test= hstack((std_sun_back_test,sun_std_back[hour]))
    std_sun_front_test= hstack((std_sun_front_test,sun_std_front[hour]))
    std_shade_test= hstack((std_shade_test,shade_std_all[hour]))
    std_cont_test= hstack((std_cont_test,con_std_all[hour]))

<h1> Friedman test... Testing weather or not three independent measurements are consistent with each other </h1>

In [199]:
# here we test the mean of sun_back, sun_front, and the control averaged over hour
chi2, p = friedmanchisquare(sun_back_test,sun_front_test,sun_back_test)
print ('chi^2 =',chi2,' p= ', p)

#if we want to test the difference between only two measurements have to use a chi^2 test taking one as the theory and the other as the experiment:
#the degrees of freedom are the number of data points - 1 for the averaging. Form that you can calulate the p value.

ValueError:
Less than 3 levels.  Friedman test not appropriate.

<h2> let's do a Chi^2 test between the sun_back and sun_front. Fine in limit of average over 1000+ data points where the central value and standard deviation are well defined </h2>

In [195]:
#take the sun back as the experiment and sun_front as the theoretical expectation
#method: X^2 = sum( ((Fe-Ft)^2/sigma^2 )

chi2= sum( (sun_front_test-sun_back_test)**2/(std_sun_back_test**2 + std_sun_front_test**2) )
p_val = chisqprob(chi2, hour_diff-1)

print('chi^2 =', chi2, ' p value of chi^2 test = ', p_val)

('chi^2 =', 14.025913256561843, ' p value of chi^2 test = ', 0.0072128089106260496)

In [196]:
#Compare Shade to Sun-front
#method: X^2 = sum( ((Fe-Ft)^2/sigma^2 )

chi2= sum( (sun_front_test-shade_test)**2/(std_sun_back_test**2 + std_shade_test**2) )
p_val = chisqprob(chi2, hour_diff-1)

print('chi^2 =', chi2, ' p value of chi^2 test = ', p_val)

('chi^2 =', 12.5643374367781, ' p value of chi^2 test = ', 0.013612864698142775)

In [197]:
f_oneway(sun_front_test,sun_back_test)

F_onewayResult(statistic=2.4837766514169384, pvalue=0.15367533169898215)